# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
    ]
