# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170827_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='org/%Y/%m', verbose_name='教师头像'),
        ),
    ]
