# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='years_old',
            field=models.IntegerField(default=0, verbose_name='年龄mig'),
        ),
    ]
