# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
        ('course', '0005_auto_20170917_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='a', max_length=200, verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='a', max_length=200, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='url'),
        ),
    ]
