# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20170917_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_bannar',
            field=models.BooleanField(default=False, verbose_name='是轮播广告位吗？'),
        ),
    ]
