# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170802_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebanner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册验证码'), ('forget', '找回验证码')], max_length=12, verbose_name='验证码类型'),
        ),
    ]
