# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170815_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册验证码'), ('forget', '找回验证码'), ('update', '更新邮箱')], max_length=30, verbose_name='验证码类型'),
        ),
    ]
